---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/books":
    get:
      summary: Get all books
      tags:
      - Books
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        required: true
        description: Authorization token
        schema:
          type: string
      responses:
        '200':
          description: books found
        '401':
          description: unauthorized
    post:
      summary: Create a book
      tags:
      - Books
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        required: true
        description: Authorization token
        schema:
          type: string
      responses:
        '302':
          description: redirected
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                book:
                  title:
                    type: string
                  body:
                    type: string
              required:
              - title
              - body
          application/xml:
            schema:
              type: object
              properties:
                book:
                  title:
                    type: string
                  body:
                    type: string
              required:
              - title
              - body
  "/api/v1/books/{id}":
    get:
      summary: Get a book
      tags:
      - Books
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        required: true
        description: Authorization token
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: ID of the book
        schema:
          type: string
      responses:
        '200':
          description: book found
        '404':
          description: book not found
        '401':
          description: unauthorized
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
